env:
  matrix:
    - ARCH=x86_64
  global:
    - ZMQ_VERSION=4.1.4

language: cpp
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
 - sudo apt-get update -y
 - sudo apt-get install libpgm-dev -y
install:
 - git clone -b stable git://github.com/jedisct1/libsodium.git
 - git clone https://github.com/zeromq/libzmq.git
 - git clone https://github.com/zeromq/jzmq.git
 - wget http://download.zeromq.org/zeromq-${ZMQ_VERSION}.tar.gz
 - tar xzvf zeromq-${ZMQ_VERSION}.tar.gz
script:
 - cd libsodium
 - ./autogen.sh
 - ./configure --prefix=${HOME}/${ARCH}
 - make
 - make install
 - cd ..
 - cd zeromq-${ZMQ_VERSION}
 - ./autogen.sh
 - ./configure --with-libsodium --prefix=${HOME}/${ARCH}
 - CPPFLAGS="-I${HOME}/${ARCH}/include" LDFLAGS="-L${HOME}/${ARCH}/lib -lsodium" make
 - make install
 - ldconfig
 - cd ..
 - cd jzmq/jzmq-jni
 - ./autogen.sh
 - ./configure --prefix=${HOME}/${ARCH}
 - CPPFLAGS="-I${HOME}/${ARCH}/include" LDFLAGS="-L${HOME}/${ARCH}/lib" make
 - make install
 - cd ../..
addons:
  artifacts:
    debug: true
    paths:
     - ${HOME}/${ARCH}/libjzmq.so
     - ${HOME}/${ARCH}/libzmq.so
     - ${HOME}/${ARCH}/libsodium.so
    target_paths: ${ZMQ_VERSION}/${ARCH}

