env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
      CFLAGS=-m32
      CXXFLAGS=-m32
      LDFLAGS=-m32
  global:
    - ZMQ_VERSION=4.1.4
language: cpp
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
 - sudo apt-get update -y
 - sudo apt-get install libpgm-dev gcc-multilib g++-multilib mingw32 mingw-w64 -y
install:
 - git clone -b stable git://github.com/jedisct1/libsodium.git
 - git clone https://github.com/zeromq/libzmq.git
 - git clone https://github.com/zeromq/jzmq.git
 - wget http://download.zeromq.org/zeromq-${ZMQ_VERSION}.tar.gz
 - tar xzvf zeromq-${ZMQ_VERSION}.tar.gz
script:
 - cd libsodium
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo ldconfig
 - cd ..
 - cd zeromq-${ZMQ_VERSION}
 - ./autogen.sh
 - ./configure --with-libsodium LDFLAGS="$LDFLAGS -Wl,-Bstatic,-lsodium -Wl,-Bdynamic" CXXFLAGS="$CXXFLAGS -fPIC"
 - make
 - sudo make install
 - sudo ldconfig
 - cd ..
 - cd jzmq/jzmq-jni
 - ./autogen.sh
 - LDFLAGS="$LDFLAGS -lrt -lpthread" ./configure --enable-self-contained
 - make
 - sudo make install
 - cd
 - cp /usr/local/lib/libjzmq.so.0.0.0 libjzmq.so
addons:
  artifacts:
    debug: true
    paths:
     - libjzmq.so
    target_paths: ${ZMQ_VERSION}/${ARCH}
    permissions: public-read

