env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
      CFLAGS=-m32
      CXXFLAGS=-m32
      LDFLAGS=-m32
  global:
    - ZMQ_VERSION=4.1.4

language: cpp
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
 - sudo apt-get update -y
 - sudo apt-get install libpgm-dev gcc-multilib -y
install:
 - git clone -b stable git://github.com/jedisct1/libsodium.git
 - git clone https://github.com/zeromq/libzmq.git
 - git clone https://github.com/zeromq/jzmq.git
 - wget http://download.zeromq.org/zeromq-${ZMQ_VERSION}.tar.gz
 - tar xzvf zeromq-${ZMQ_VERSION}.tar.gz
script:
 - export CPPFLAGS="$CPPFLAGS -I${HOME}/${ARCH}/include"
 - export LDFLAGS="$LDFLAGS -L${HOME}/${ARCH}/lib"
 - cd libsodium
 - ./autogen.sh
 - ./configure --prefix=${HOME}/${ARCH}
 - make clean install
 - cd ..
 - cd zeromq-${ZMQ_VERSION}
 - ./autogen.sh
 - LDFLAGS="$LDFLAGS -lsodium" sodium_CFLAGS=${HOME}/${ARCH}/include sodium_LIBS=${HOME}/${ARCH}/libs ./configure --with-libsodium --prefix=${HOME}/${ARCH}
 - make clean install
 - ldconfig
 - cd ..
 - cd jzmq/jzmq-jni
 - ./autogen.sh
 - ./configure --prefix=${HOME}/${ARCH}
 - make clean install
 - cd ../..
addons:
  artifacts:
    debug: true
    paths:
     - ${HOME}/${ARCH}/libjzmq.so*
     - ${HOME}/${ARCH}/libzmq.so*
     - ${HOME}/${ARCH}/libsodium.so*
    target_paths: ${ZMQ_VERSION}/${ARCH}

