env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
      CFLAGS=-m32
      CPPFLAGS=-m32
      CXXFLAGS=-m32
      LDFLAGS=-m32
      HOSTBUILD="--host=i686-pc-linux-gnu --build=x86_64-pc-linux-gnu"
  global:
    - ZMQ_VERSION=4.1.4
language: cpp
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
 - sudo apt-get update -y
 - sudo apt-get install libpgm-dev gcc-multilib g++-multilib mingw32 mingw-w64 -y
install:
 - git clone https://github.com/zeromq/jzmq.git
 - wget http://download.zeromq.org/zeromq-${ZMQ_VERSION}.tar.gz
 - tar xzvf zeromq-${ZMQ_VERSION}.tar.gz
script:
 - cd zeromq-${ZMQ_VERSION}
 - ./autogen.sh
 - CXXFLAGS="$CXXFLAGS -fPIC" ./configure --without-libsodium --prefix=${HOME}/${ARCH} $HOSTBUILD
 - make V=1 install
 - cd ..
 - cd jzmq/jzmq-jni
 - ./autogen.sh
 - CPPFLAGS="$CPPFLAGS -I${HOME}/${ARCH}/include" LDFLAGS="$LDFLAGS -L${HOME}/${ARCH}/lib -lrt -lpthread" ./configure --prefix=${HOME}/${ARCH} --enable-self-contained $HOSTBUILD
 - make install
 - cd
 - cp ${HOME}/${ARCH}/lib/libjzmq.so.0.0.0 libjzmq.so
addons:
  artifacts:
    debug: true
    paths:
     - libjzmq.so
    target_paths: ${ZMQ_VERSION}/${ARCH}
    permissions: public-read
