language: cpp
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
 - sudo apt-get update -y
 - sudo apt-get install libpgm-dev -y
install:
 - git clone -b stable git://github.com/jedisct1/libsodium.git
 - git clone https://github.com/zeromq/libzmq.git
 - git clone https://github.com/zeromq/jzmq.git
script:
 - cd libsodium
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - sudo ldconfig
 - cd ..
 - cd libzmq
 - ./autogen.sh
 - ./configure --with-libsodium
 - LDFLAGS=-lsodium make
 - sudo make install
 - sudo ldconfig
 - cd ..
 - cd jzmq/jzmq-jni
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
 - cd ../..
addons:
  artifacts:
    debug: true
    paths:
     - /usr/local/lib/libjzmq.so
     - /usr/local/lib/libzmq.so
     - /usr/local/lib/libsodium.so
